// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: pkg/grpc/message.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_pkg_grpc_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_message_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMessageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageResponse) Reset() {
	*x = CreateMessageResponse{}
	mi := &file_pkg_grpc_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageResponse) ProtoMessage() {}

func (x *CreateMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageResponse.ProtoReflect.Descriptor instead.
func (*CreateMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_message_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMessageResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_pkg_grpc_message_proto protoreflect.FileDescriptor

const file_pkg_grpc_message_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/grpc/message.proto\x12\amessage\"D\n" +
	"\x14CreateMessageRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\x15CreateMessageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id2\xac\x01\n" +
	"\aMessage\x12N\n" +
	"\vSendMessage\x12\x1d.message.CreateMessageRequest\x1a\x1e.message.CreateMessageResponse\"\x00\x12Q\n" +
	"\x10SendMessageDummy\x12\x1d.message.CreateMessageRequest\x1a\x1e.message.CreateMessageResponseB\n" +
	"Z\bpkg/grpcb\x06proto3"

var (
	file_pkg_grpc_message_proto_rawDescOnce sync.Once
	file_pkg_grpc_message_proto_rawDescData []byte
)

func file_pkg_grpc_message_proto_rawDescGZIP() []byte {
	file_pkg_grpc_message_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_message_proto_rawDesc), len(file_pkg_grpc_message_proto_rawDesc)))
	})
	return file_pkg_grpc_message_proto_rawDescData
}

var file_pkg_grpc_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_grpc_message_proto_goTypes = []any{
	(*CreateMessageRequest)(nil),  // 0: message.CreateMessageRequest
	(*CreateMessageResponse)(nil), // 1: message.CreateMessageResponse
}
var file_pkg_grpc_message_proto_depIdxs = []int32{
	0, // 0: message.Message.SendMessage:input_type -> message.CreateMessageRequest
	0, // 1: message.Message.SendMessageDummy:input_type -> message.CreateMessageRequest
	1, // 2: message.Message.SendMessage:output_type -> message.CreateMessageResponse
	1, // 3: message.Message.SendMessageDummy:output_type -> message.CreateMessageResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpc_message_proto_init() }
func file_pkg_grpc_message_proto_init() {
	if File_pkg_grpc_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_message_proto_rawDesc), len(file_pkg_grpc_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_message_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_message_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_message_proto_msgTypes,
	}.Build()
	File_pkg_grpc_message_proto = out.File
	file_pkg_grpc_message_proto_goTypes = nil
	file_pkg_grpc_message_proto_depIdxs = nil
}
