name: sister-tugas-4
services:
  rabbitmq:
    image: rabbitmq:4.1.4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rizalanggoro
      RABBITMQ_DEFAULT_PASS: 130603

  database:
    image: postgres:17.5-alpine3.22
    ports:
      - "15432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "sister_tugas_4"